spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sococim_db?useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:postgresql://localhost:5332/customer
    #prefer postgres cause enabling allowPublicKeyRetrieval can lead to MITM attack which can cause
    #attacker to get the password
    username: sococim_user
    password: passer
  jpa:
    hibernate:
     ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  thymeleaf:
    prefix: file:///C:///Users//Adja//Desktop//M2//Sococim//demo_sec//target//classes/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      resolve-lazily: false
      max-request-size: 1MB
  mail:
    host: smtp.gmail.com
    port: 645
    username: socindustries12@gmail.com
    password: yscgyvakovrtaznl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true
    protocol: smtp

server:
  port: 8081

