spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sococim_db?useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:postgresql://localhost:5332/customer
    #prefer postgres cause enabling allowPublicKeyRetrieval can lead to MITM attack which can cause
    #attacker to get the password
    username: sococim_user
    password: socpass
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
